# Welcome to Jekyll!

title: DJ Freddie B
tagline: Think Differently
email: dj.freddieb@gmail.com
description: Think Differently
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://djfreddieb.shotlow.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: djfreddiebenz
github_username:  fbs70

timezone: TIMEZONE

permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
theme: minima
gems:
  #- jekyll-feed
  - jekyll-paginate
  - jekyll-admin

include:
  - .nojekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - bower.json
  - node_modules
  - package.json
  - Gruntfile.coffee
  - Rakefile
